###
#  This action installs the Genesys Cloud python SDK and then installs archy.
#  It also adds Archy to the path
#
###
name: "Setup Genesys Cloud Tools"
description: "Installs Archy and the Genesys Cloud CLI"
runs:
  using: "composite"
  steps:
    - run: |
        pip install PureCloudPlatformClientV2
        mkdir output
        # mkdir archy
        # cd archy
        # wget -q https://sdk-cdn.mypurecloud.com/archy/latest/archy-linux.zip
        # unzip archy-linux.zip
        # . archy version                            
        # export PATH=$PATH:$GITHUB_WORKSPACE/archy
        # cd ..
        # pwd
        # archy version
      shell: bash
